name: Redeploy ECS Service
description: |-
  Force a new deployment on an ECS service to pull the latest image/environment variables.

inputs:
  cluster:
    description: 'The name of the ECS cluster'
    required: true
  service:
    description: 'The name of the ECS service'
    required: true

runs:
  using: node20
  main: action.js
